# DecentralChain Testnet configuration
# Chain ID: ! (33)

waves {
  blockchain {
    type = TESTNET
  }

  network {
    node-name = "DCC testnet node"

    # Testnet P2P port
    port = 6863

    known-peers = [
      "159.69.126.149:6863"
      "94.130.105.239:6863"
      "159.69.126.153:6863"
      "94.130.172.201:6863"
    ]
  }

  wallet {
    # seed = ""
  }

  rest-api {
    enable = yes
    bind-address = "0.0.0.0"
    port = 6869
    # api-key-hash = ""
    cors = yes
  }

  miner {
    enable = yes
    quorum = 1
  }

  # Uncomment to enable the gRPC extension
  # extensions += com.wavesplatform.api.grpc.GRPCServerExtension
}
