# DecentralChain Stagenet configuration
# Chain ID: S (83)

waves {
  blockchain {
    type = STAGENET
  }

  network {
    node-name = "DCC stagenet node"

    # Stagenet P2P port
    port = 6862

    known-peers = [
      "88.99.185.128:6862"
      "95.216.205.3:6862"
      "49.12.15.166:6862"
      "88.198.179.16:6862"
    ]
  }

  wallet {
    # seed = ""
  }

  rest-api {
    enable = yes
    bind-address = "0.0.0.0"
    port = 6869
    # api-key-hash = ""
    cors = yes
  }

  miner {
    enable = yes
    quorum = 1
  }

  # Uncomment to enable the gRPC extension
  # extensions += com.wavesplatform.api.grpc.GRPCServerExtension
}
