# DecentralChain Mainnet configuration
# Chain ID: ? (63)

waves {
  blockchain {
    type = MAINNET
  }

  network {
    node-name = "DCC mainnet node"

    # Mainnet P2P port
    port = 6868

    known-peers = [
      "168.119.116.189:6868"
      "135.181.87.72:6868"
      "35.158.218.156:6868"
      "52.48.34.89:6868"
    ]
  }

  wallet {
    # seed = ""
  }

  rest-api {
    enable = yes
    bind-address = "127.0.0.1"
    port = 6869
    # api-key-hash = ""
  }

  miner {
    enable = yes
    quorum = 1
  }

  # Uncomment to enable the gRPC extension
  # extensions += com.wavesplatform.api.grpc.GRPCServerExtension
}
