package com.decentralchain.network

import com.decentralchain.common.utils.Base64
import com.decentralchain.test.*

class MicroBlockResponseSpec extends FreeSpec {
  private val microBlockBytes = Base64.decode(
    "CsQCCAMSQAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEaQAICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIiIHmMvWTXjEoPujOLKmNJY0lA3E5bYB2xAp4CxB4P4FZ5KpkBClUIPxIgeYy9ZNeMSg+6M4sqY0ljSUDcTltgHbECngLEHg/gVnkaBBDAhD0gmouBlfIzKALCBh8KFgoUPTrYhPoEKSe51sN99wr1wL2VFsUSBRCAwtcvEkC8rvLX+7FUSgSaRvO+rbIwYlkL25ZNVfROkBfjs3WT7f8BbrCSDx+Tw4hh7EFY7fHmuOk9yo9IVUshW/B7gNqNEkC05ZCAp5NbRgVrSywfy97k2WDE/DiyZE2L8eBvBX5IMn7/FoH6eFK1/S+hsetAb1CV+NvKbaChOWR5Q6eHJRSKGkACAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIC"
  )

  "Signature is valid" in {
    val parsedMicroBlock = PBMicroBlockSpec.deserializeData(microBlockBytes).get.microblock
    parsedMicroBlock.signatureValid() shouldBe true
  }
}
