package com.decentralchain.network

import com.decentralchain.common.utils.Base64
import com.decentralchain.test.*

class MicroBlockResponseSpec extends FreeSpec {
  private val microBlockBytes = Base64.decode(
    "CqQCCAUSIAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBGkACAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICIiB5jL1k14xKD7oziypjSWNJQNxOW2AdsQKeAsQeD+BWeSqZAQpVCD8SIHmMvWTXjEoPujOLKmNJY0lA3E5bYB2xAp4CxB4P4FZ5GgQQwIQ9INjSn6z3MygCwgYfChYKFD062IT6BCknudbDffcK9cC9lRbFEgUQgMLXLxJAnuZxFcledIy0q/5iT4Lo58AJpYDunUzA8Evh43DMC68vkpgwDxBSY84Tr0zLk/Ob0hJ/psyk7xcC9hF0JBYBixJA0LWMkd/6e7I/xpfwjfAEj0Io9sHZYIpOBFnXHvVsYYw8hCtryKMkTFIE95ZUuXf7MawoJSU7u8dOyW3GBL+FiRpAAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg=="
  )

  "Signature is valid" in {
    val parsedMicroBlock = PBMicroBlockSpec.deserializeData(microBlockBytes).get.microblock
    parsedMicroBlock.signatureValid() shouldBe true
  }
}
