# NPM registry supports only one source workflow per package: https://docs.npmjs.com/trusted-publishers#for-github-actions
name: Publish packages to NPMJS
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Package version
        required: true
      tag:
        description: Package tag
        required: true
        default: snapshot

permissions:
  contents: read

concurrency:
  group: "npm-packages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: NPMJS
      url: ${{ steps.publish.outputs.url }}
    permissions:
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: proudust/gh-describe@80412be8ce0e77d8afba6b340e34790bc772aa45  # v2.2.0
        id: ghd
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'sbt'
      - uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b  # v1.2.1
      - run: sbt -Dproject.version=${{ steps.ghd.outputs.describe }} --batch ';lang-tests/test;lang-tests-js/test;repl/test;langJS/fullOptJS;replJS/fullOptJS'
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '>=24.7.0' # Trusted publishing requires npm CLI version 11.5.1 or later.
      - if: github.event_name == 'workflow_dispatch'
        run:
          echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          echo "TAG=${{ inputs.tag }}" >> $GITHUB_ENV
      - if: github.event_name == 'release'
        run: |
          echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> $GITHUB_ENV
          echo "TAG=latest" >> $GITHUB_ENV
      - id: publish
        run: |
          cd lang/js
          npm version $VERSION --no-git-tag-version
          npm publish --provenance --access public --tag $TAG
          cd ../../repl/js
          npm version $VERSION --no-git-tag-version
          npm publish --provenance --access public --tag $TAG
          echo "url=https://www.npmjs.com/package/@decentral-america/ride-lang/v/$VERSION" >> "$GITHUB_OUTPUT"
